version: "2017-09-20"

allow_concurrent_steps: true

dependencies:
  - id: python_base_image
    type: docker
    ref: python:3.11-slim
    autostart_on_update: true
  - id: jdk_base_image
    type: docker
    ref: eclipse-temurin:21-jdk
    autostart_on_update: true

shared_vars: &SHARED_ENV
  APPLICATION_ID: "example-service"
  TEAM_ID: "example-team"
  UV_DOWNLOAD_PYTHON: "never"
  UV_NATIVE_TLS: true
  UV_DEFAULT_INDEX: "https://example.com/pypi/simple"
  UV_PUBLISH_URL: "https://example.com/pypi/internal/"
  UV_PUBLISH_USERNAME: "root"
  UV_PUBLISH_PASSWORD: ""
  HOTVECT_VERSION: "9.36.1"
  IMAGE_NAME: &IMAGE_NAME "#{CDP_ZAPPR_TEAM}/hotvect"

pipeline:
  - id: "check-linters"
    depends_on: []
    type: script
    timeout: 15m
    vm_config:
      type: linux
      image: cdp-runtime/python-3.11
    when:
      event: pull_request
    cache:
      paths:
        - ~/.cache
    env:
      <<: *SHARED_ENV
    commands:
      - desc: "run-pre-commit"
        cmd: |
          pre-commit install
          pre-commit run --from-ref origin/HEAD --to-ref HEAD
      - desc: "Run version upgrade checks"
        cmd: |
          # The script uses only builtin libraries so it can be run directly without uv
          cd python && python scripts/check_versions.py ${HOTVECT_VERSION} ${CDP_TARGET_COMMIT_ID}

  - id: build-snapshot
    type: script
    vm_config:
      type: linux
      image: cdp-runtime/jdk21-maven
    commands:
      - desc: "Add -SNAPSHOT suffix"
        cmd: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}-SNAPSHOT -B
      - desc: "Run tests and check buildability"
        cmd: mvn clean install -B
      - desc: "Deploy snapshot version"
        cmd: mvn clean deploy -B
      - desc: "Stash hotvect offline util jar so that python step can use it"
        cmd: |
          cdp-tool stash push snapshot-hotvect-offline-util-target hotvect-offline-util/target/*-jar-with-dependencies.jar

  - id: test-python
    desc: Runs pytests
    type: script
    depends_on:
      - build-snapshot
    vm_config:
      type: linux
      image: cdp-runtime/python-3.11
    env:
      <<: *SHARED_ENV
    commands:
      - desc: "Checks install requirements"
        cmd: |
          cd python 
          uv sync --frozen --all-extras
      - desc: "Copy hotvect offline util jar"
        cmd: |
          cdp-tool stash pop stashed
          mv stashed/snapshot-hotvect-offline-util-target hotvect-offline-util/target
          ls hotvect-offline-util/target/*
      - desc: "Runs unittests"
        cmd: |
          cd python
          uv run scripts/copy_jar.py
          uv run pytest

  - id: build-docs
    depends_on: []
    type: script
    vm_config:
      type: linux
      image: cdp-runtime/mkdocs-v9
      size: small
    commands:
      - desc: build docs
        cmd: build-docs
      - desc: notify PR
        cmd: |
          DOCS_CHANGED=$(git diff --quiet  origin/"${CDP_TARGET_BRANCH}"..."${CDP_HEAD_COMMIT_ID}" -- docs || echo changed)
          if [ "$CDP_PULL_REQUEST_NUMBER" ] && [ "$DOCS_CHANGED" == "changed" ]; then
            comment="Docs have changed. Preview is available under: https://example.com/docs-preview/pr/#{CDP_PULL_REQUEST_NUMBER}/"
            git gh-comment "$comment"
          fi
    artifacts:
      - type: docs
        name: hotvect
        path: site

  - id: build-training-image-stg
    desc: Builds training docker image.
    type: script
    vm_config:
      type: linux
      image: cdp-runtime/python-3.11
    depends_on:
      - build-snapshot
    when:
      event: pull_request
    env:
      <<: *SHARED_ENV
    commands:
      - desc: "Copy hotvect offline util jar"
        cmd: |
          cdp-tool stash pop stashed
          mv stashed/snapshot-hotvect-offline-util-target hotvect-offline-util/target
          ls hotvect-offline-util/target/*
      - desc: "Verifies that building the docker image works and pushes to staging"
        cmd: |
          # Need to copy the certificates so requests to internal pypi work from the container
          # https://example.com/docs/faq/#docker-build-is-unable-to-access-nexus-from-cdp
          cp -r /usr/local/share/ca-certificates/cdp ./cdp-certs 
          
          EXTRA_VERSION=".dev${CDP_TARGET_REPOSITORY_COUNTER}"
          TAG="${CDP_REGISTRY}/${IMAGE_NAME}:${HOTVECT_VERSION}${EXTRA_VERSION}"
          uv run --project=python python/scripts/copy_jar.py
          docker build --network=host -t ${TAG} --build-arg BASE_IMAGE=${DEP_PYTHON_BASE_IMAGE_REF} --build-arg BASE_IMAGE_VERSION=${DEP_PYTHON_BASE_IMAGE_VERSION} --build-arg BASE_JDK_IMAGE=${DEP_JDK_BASE_IMAGE_REF} --build-arg BASE_JDK_IMAGE_VERSION=${DEP_JDK_BASE_IMAGE_VERSION} .
          docker push ${TAG}

  - id: build-release
    type: script
    depends_on:
      - build-snapshot
      - test-python
    vm_config:
      type: linux
      image: cdp-runtime/jdk21-maven
    requires_human_approval: false
    commands:
      - desc: "Deploy release version"
        cmd: mvn clean deploy -B -X
      - desc: "Push tag"
        cmd: |
          export TAG=`mvn -U -B -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin::exec`
          git gh-tag $TAG
      - desc: "Stash hotvect offline util jar so that python step can use it"
        cmd: |
          cdp-tool stash push hotvect-offline-util-target hotvect-offline-util/target/*-jar-with-dependencies.jar
    when:
      event: push

  - id: publish-python
    type: script
    vm_config:
      type: linux
      image: cdp-runtime/python-3.11
    when:
      event: push
    depends_on:
      - build-release
    env:
      <<: *SHARED_ENV
    commands:
      - desc: "Copy hotvect offline util jar"
        cmd: |
          cdp-tool stash pop stashed
          mv stashed/hotvect-offline-util-target hotvect-offline-util/target
          ls hotvect-offline-util/target/*
      - desc: Publishes the package to internal PyPI
        cmd: |
          cd python
          uv run scripts/copy_jar.py
          uv build
          uv publish

  - id: build-training-image
    desc: Builds training docker image.
    type: script
    vm_config:
      type: linux
      image: cdp-runtime/python-3.11
    depends_on:
      - build-release
    when:
      event: push
    env:
      <<: *SHARED_ENV
    commands:
      # Push to ZCR. See details: https://github.com/zalando-build/zflow-examples/blob/01150415d6135349fa577fcd0695c13e74b61924/sagemaker-custom-image/README.md
      # https://example.com/docs/concepts/builds/#publishing-artifacts
      # https://example.com/docs/concepts/builds/#zalando-container-registry-zcr-images
      - desc: "Copy hotvect offline util jar"
        cmd: |
          cdp-tool stash pop stashed
          mv stashed/hotvect-offline-util-target hotvect-offline-util/target
          ls hotvect-offline-util/target/*
      - desc: "Verifies that building the docker image works and pushes to staging"
        cmd: |
          # Need to copy the certificates so requests to internal pypi work from the container
          # https://example.com/docs/faq/#docker-build-is-unable-to-access-nexus-from-cdp
          cp -r /usr/local/share/ca-certificates/cdp ./cdp-certs 
          
          TAG="${CDP_REGISTRY}/${IMAGE_NAME}:${HOTVECT_VERSION}"
          uv run --project=python python/scripts/copy_jar.py
          docker build --network=host -t ${TAG} --build-arg BASE_IMAGE=${DEP_PYTHON_BASE_IMAGE_REF} --build-arg BASE_IMAGE_VERSION=${DEP_PYTHON_BASE_IMAGE_VERSION} --build-arg BASE_JDK_IMAGE=${DEP_JDK_BASE_IMAGE_REF} --build-arg BASE_JDK_IMAGE_VERSION=${DEP_JDK_BASE_IMAGE_VERSION} .
          docker push ${TAG}
          cdp-promote-image ${TAG}
